### ISSUE TITLE
Persistent Script and Crontab

### ISSUE THREAD

**Issue by DKeppi** [FastEddy1114/uxg-lite-blocklist#1]
Hi FastEddy1114,

i put my Shellscript into a new folder in /data/custom/ and the cronjob in /etc/crontab file with a "service cron reload" command afterwards.
After my last update its still there.

Maybe you can give it a try ;)

BR DKeppi

**Comment by FastEddy1114** [comment]
Hi DKeppi,

I'll definitely give it a try!  Thank you for taking the time to find a possible solution to this known issue for me!

**Comment by FastEddy1114** [comment]
Now that a new firmware has finally come out for the UXG-Lite I can confirm your suggestion does indeed work to fix the issue and keep the crontab file settings persistent across firmware upgrades!  Editing the main /etc/crontab file is what was needed rather than creating a user level crontab file as the user level file gets erased on firmware upgrades.  Again thank you for finding this solution.

**Comment by DKeppi** [comment]
you are welcome...was my pleasure
